
package servidorsalidas;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "SalidaLlenaException", targetNamespace = "http://servidorSalidas/")
public class SalidaLlenaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SalidaLlenaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SalidaLlenaException_Exception(String message, SalidaLlenaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public SalidaLlenaException_Exception(String message, SalidaLlenaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidorsalidas.SalidaLlenaException
     */
    public SalidaLlenaException getFaultInfo() {
        return faultInfo;
    }

}
