
package servidorsalidas;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "SalidaInvalidaException", targetNamespace = "http://servidorSalidas/")
public class SalidaInvalidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SalidaInvalidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SalidaInvalidaException_Exception(String message, SalidaInvalidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public SalidaInvalidaException_Exception(String message, SalidaInvalidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidorsalidas.SalidaInvalidaException
     */
    public SalidaInvalidaException getFaultInfo() {
        return faultInfo;
    }

}
