
package servidorsalidas;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSSalidasService", targetNamespace = "http://servidorSalidas/", wsdlLocation = "http://localhost:3333/wss?wsdl")
public class WSSalidasService
    extends Service
{

    private final static URL WSSALIDASSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSALIDASSERVICE_EXCEPTION;
    private final static QName WSSALIDASSERVICE_QNAME = new QName("http://servidorSalidas/", "WSSalidasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	Properties properties = new Properties();
			properties.load(new FileInputStream(new File(System.getProperty("user.home") + "/.turismoUy/conf.properties")));
            url = new URL((String) properties.get("WSS.IP") + "?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (FileNotFoundException e1) {
			e1.printStackTrace();
		} catch (IOException e1) {
			e1.printStackTrace();
		}
        WSSALIDASSERVICE_WSDL_LOCATION = url;
        WSSALIDASSERVICE_EXCEPTION = e;
    }

    public WSSalidasService() {
        super(__getWsdlLocation(), WSSALIDASSERVICE_QNAME);
    }

    public WSSalidasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSALIDASSERVICE_QNAME, features);
    }

    public WSSalidasService(URL wsdlLocation) {
        super(wsdlLocation, WSSALIDASSERVICE_QNAME);
    }

    public WSSalidasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSALIDASSERVICE_QNAME, features);
    }

    public WSSalidasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSalidasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSSalidas
     */
    @WebEndpoint(name = "WSSalidasPort")
    public WSSalidas getWSSalidasPort() {
        return super.getPort(new QName("http://servidorSalidas/", "WSSalidasPort"), WSSalidas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSalidas
     */
    @WebEndpoint(name = "WSSalidasPort")
    public WSSalidas getWSSalidasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidorSalidas/", "WSSalidasPort"), WSSalidas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSALIDASSERVICE_EXCEPTION!= null) {
            throw WSSALIDASSERVICE_EXCEPTION;
        }
        return WSSALIDASSERVICE_WSDL_LOCATION;
    }

}
