
package servidoractividades;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "DepartamentoInvalidoException", targetNamespace = "http://servidorActividades/")
public class DepartamentoInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DepartamentoInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DepartamentoInvalidoException_Exception(String message, DepartamentoInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public DepartamentoInvalidoException_Exception(String message, DepartamentoInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidoractividades.DepartamentoInvalidoException
     */
    public DepartamentoInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
