
package servidoractividades;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TieneSalidaVigenteException", targetNamespace = "http://servidorActividades/")
public class TieneSalidaVigenteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TieneSalidaVigenteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TieneSalidaVigenteException_Exception(String message, TieneSalidaVigenteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TieneSalidaVigenteException_Exception(String message, TieneSalidaVigenteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidoractividades.TieneSalidaVigenteException
     */
    public TieneSalidaVigenteException getFaultInfo() {
        return faultInfo;
    }

}
