
package servidorpaquetes;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CantidadTuristaException", targetNamespace = "http://servidorPaquetes/")
public class CantidadTuristaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CantidadTuristaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CantidadTuristaException_Exception(String message, CantidadTuristaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CantidadTuristaException_Exception(String message, CantidadTuristaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidorpaquetes.CantidadTuristaException
     */
    public CantidadTuristaException getFaultInfo() {
        return faultInfo;
    }

}
