
package servidorpaquetes;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PaqueteInvalidoException", targetNamespace = "http://servidorPaquetes/")
public class PaqueteInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PaqueteInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PaqueteInvalidoException_Exception(String message, PaqueteInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PaqueteInvalidoException_Exception(String message, PaqueteInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidorpaquetes.PaqueteInvalidoException
     */
    public PaqueteInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
