
package servidorpaquetes;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSPaquetes", targetNamespace = "http://servidorPaquetes/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSPaquetes {


    /**
     * 
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/getFileRequest", output = "http://servidorPaquetes/WSPaquetes/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://servidorPaquetes/WSPaquetes/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns servidorpaquetes.StringDTPaqueteMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/obtenerPaquetesConAlmenosUnaActividadRequest", output = "http://servidorPaquetes/WSPaquetes/obtenerPaquetesConAlmenosUnaActividadResponse")
    public StringDTPaqueteMap obtenerPaquetesConAlmenosUnaActividad();

    /**
     * 
     * @return
     *     returns servidorpaquetes.StringDTDepartamentoMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/obtenerDepartamentosRequest", output = "http://servidorPaquetes/WSPaquetes/obtenerDepartamentosResponse")
    public StringDTDepartamentoMap obtenerDepartamentos();

    /**
     * 
     * @return
     *     returns servidorpaquetes.StringDTPaqueteMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/obtenerDatosPaquetesRequest", output = "http://servidorPaquetes/WSPaquetes/obtenerDatosPaquetesResponse")
    public StringDTPaqueteMap obtenerDatosPaquetes();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorpaquetes.StringDTActividadMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/actsEnPaqRequest", output = "http://servidorPaquetes/WSPaquetes/actsEnPaqResponse")
    public StringDTActividadMap actsEnPaq(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorpaquetes.SetOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/categoriasEnPaqRequest", output = "http://servidorPaquetes/WSPaquetes/categoriasEnPaqResponse")
    public SetOfString categoriasEnPaq(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws CantidadTuristaException_Exception
     * @throws PaqueteCompradoException_Exception
     * @throws PaqueteInvalidoException_Exception
     */
    @WebMethod
    @Action(input = "http://servidorPaquetes/WSPaquetes/comprarPaqueteRequest", output = "http://servidorPaquetes/WSPaquetes/comprarPaqueteResponse", fault = {
        @FaultAction(className = CantidadTuristaException_Exception.class, value = "http://servidorPaquetes/WSPaquetes/comprarPaquete/Fault/CantidadTuristaException"),
        @FaultAction(className = PaqueteInvalidoException_Exception.class, value = "http://servidorPaquetes/WSPaquetes/comprarPaquete/Fault/PaqueteInvalidoException"),
        @FaultAction(className = PaqueteCompradoException_Exception.class, value = "http://servidorPaquetes/WSPaquetes/comprarPaquete/Fault/PaqueteCompradoException")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws CantidadTuristaException_Exception, PaqueteCompradoException_Exception, PaqueteInvalidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorpaquetes.DtPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/seleccionarPaqueteRequest", output = "http://servidorPaquetes/WSPaquetes/seleccionarPaqueteResponse")
    public DtPaquete seleccionarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://servidorPaquetes/WSPaquetes/guardarImgRequest", output = "http://servidorPaquetes/WSPaquetes/guardarImgResponse")
    public void guardarImg(
        @WebParam(name = "arg0", partName = "arg0")
        boolean arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        byte[] arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns servidorpaquetes.StringDTPaqueteMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/busquedaRequest", output = "http://servidorPaquetes/WSPaquetes/busquedaResponse")
    public StringDTPaqueteMap busqueda(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @return
     *     returns servidorpaquetes.StringDTCategoriaMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidorPaquetes/WSPaquetes/obtenerCategoriasRequest", output = "http://servidorPaquetes/WSPaquetes/obtenerCategoriasResponse")
    public StringDTCategoriaMap obtenerCategorias();

}
