
package servidorusuarios;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CampoIncompletoException", targetNamespace = "http://servidorUsuarios/")
public class CampoIncompletoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CampoIncompletoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CampoIncompletoException_Exception(String message, CampoIncompletoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CampoIncompletoException_Exception(String message, CampoIncompletoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidorusuarios.CampoIncompletoException
     */
    public CampoIncompletoException getFaultInfo() {
        return faultInfo;
    }

}
